# Generated by Django 3.1.6 on 2021-05-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=20)),
                ('lastlogin', models.DateTimeField(max_length=20)),
                ('lastlogout', models.DateTimeField(max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
